package ai

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
)

// GroqClient defines the interface for AI operations
type GroqClient interface {
	AnalyzeLog(systemPrompt string, userMessage string) (string, error)
}

type groqClient struct {
	apiKey string
	apiURL string
	model  string
}

func NewGroqClient() GroqClient {
	url := os.Getenv("GROQ_API_URL")
	if url == "" {
		url = "https://api.groq.com/openai/v1/chat/completions"
	}
	model := os.Getenv("AI_MODEL")
	if model == "" {
		model = os.Getenv("GROQ_MODEL") // legacy fallback
	}
	if model == "" {
		model = "llama3-8b-8192"
	}
	return &groqClient{
		apiKey: os.Getenv("GROQ_API_KEY"),
		apiURL: url,
		model:  model,
	}
}

func (c *groqClient) AnalyzeLog(systemPrompt string, userMessage string) (string, error) {
	if c.apiKey == "" {
		return "", errors.New("GROQ_API_KEY is not configured")
	}

	payload := map[string]interface{}{
		"model": c.model,
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": userMessage},
		},
		"temperature": 0.2, // Low temperature for consistent analysis
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", c.apiURL, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}

	req.Header.Set("Authorization", "Bearer "+c.apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("groq API error (status %d): %s", resp.StatusCode, string(respBody))
	}

	var groqResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&groqResp); err != nil {
		return "", err
	}

	if len(groqResp.Choices) == 0 {
		return "", errors.New("no response generated by AI")
	}

	return groqResp.Choices[0].Message.Content, nil
}
